FROM python:3.9
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
WORKDIR /code
COPY . .

RUN tar -xvzf ta-lib-0.4.0-src.tar.gz && \
  cd ta-lib/ && \
  ./configure --build=aarch64-unknown-linux-gnu && \
  make && \
  make install && pip install ta-lib

RUN rm -R ta-lib ta-lib-0.4.0-src.tar.gz
RUN pip install -r requirements.txt
ENV LD_LIBRARY_PATH=/usr/local/lib