# Generated by Django 3.2.8 on 2021-10-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market_Details',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('current_price', models.FloatField()),
                ('market_cap', models.BigIntegerField()),
                ('market_cap_rank', models.BigIntegerField()),
                ('fully_diluted_valuation', models.BigIntegerField()),
                ('total_volume', models.BigIntegerField()),
                ('high_24h', models.FloatField()),
                ('low_24h', models.FloatField()),
                ('price_change_24h', models.FloatField()),
                ('price_change_percentage_24h', models.FloatField()),
                ('market_cap_change_24h', models.FloatField()),
                ('market_cap_change_percentage_24h', models.FloatField()),
                ('circulating_supply', models.BigIntegerField()),
                ('total_supply', models.BigIntegerField()),
                ('max_supply', models.BigIntegerField()),
                ('ath', models.FloatField()),
                ('ath_change_percentage', models.FloatField()),
                ('ath_date', models.DateField()),
                ('atl', models.DateField()),
                ('atl_change_percentage', models.FloatField()),
                ('roi', models.FloatField()),
                ('last_updated', models.DateField()),
            ],
        ),
    ]
