# Generated by Django 3.2.8 on 2021-10-25 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_details',
            name='atl_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='market_details',
            name='atl',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='market_details',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
