# Generated by Django 3.2.8 on 2021-10-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0002_auto_20211025_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='market_details',
            name='name',
            field=models.CharField(default='na', max_length=200),
            preserve_default=False,
        ),
    ]
